services:
  backend:
    container_name: backend
    build:
      context: ./backend
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/be
      - be-nm:/usr/be/node_modules
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - stormenergy-be

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - stormenergy-be

  influxdb2:
    container_name: influxdb
    image: influxdb:2
    restart: unless-stopped
    ports:
      - 8086:8086
    # volumes:
    #   - type: volume
    #     source: influxdb2-data
    #     target: /var/lib/influxdb2
    #   - type: volume
    #     source: influxdb2-config
    #     target: /etc/influxdb2
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_ADMIN_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
    # networks:
    #   - stormenergy-be

volumes:
  be-nm:
  postgres-data:
  influxdb2-data:
  influxdb2-config:

networks:
  stormenergy-be:
